name = "intangible-thaumcraft"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02079d5dd15fb60e09b3e2f66901038cf648eeb23e9cc274ace5801187fc6690"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
