name = "intangible-thaumcraft"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fe616b5358739ddc19b58c8121ed46b82392037e37e7bbe930b0f231ffbddb1"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
