name = "intangible-thaumcraft"
author = "flashgnash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ab3554aaa65903e1bbb1f68a2466e956e83d62cf7ab95f6e97597e4e988f57a"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
